name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "termproject/Front end/**"
      - "termproject/Back end/**"
      - "termproject/docker-compose.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/frontend_js
      IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/backend_js

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t $IMAGE_FRONTEND:${{ github.sha }} -t $IMAGE_FRONTEND:latest -f "termproject/Front end/Dockerfile" "Front end"
          docker push $IMAGE_FRONTEND:${{ github.sha }}
          docker push $IMAGE_FRONTEND:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t $IMAGE_BACKEND:${{ github.sha }} -t $IMAGE_BACKEND:latest -f "termproject/Back end/Dockerfile" "Back end"
          docker push $IMAGE_BACKEND:${{ github.sha }}
          docker push $IMAGE_BACKEND:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            
            # Stop and remove existing containers
            docker-compose down
            
            docker pull $DOCKER_USERNAME/frontend_js:latest
            docker pull $DOCKER_USERNAME/backend_js:latest
            docker-compose up -d
